### ISSUE TITLE
Don't use `path`

### ISSUE THREAD

**Issue by kotx** [ArkinSolomon/discord-emoji-converter#4]
`path` is a Node.js built-in, which means this won't run on environments such as the browser or Cloudflare Workers. Is it possible to refactor this library to use something else?

**Comment by ArkinSolomon** [comment]
I can't say I'm too familiar with Cloudflare Workers, does the newly published 1.2.4 version work for you?

**Comment by kotx** [comment]
Unfortunately no, `fs` is also built into Node. If you're looking to embed JSON data though, maybe you can just `require('emojis.json')` or something?

**Comment by ArkinSolomon** [comment]
I could do that, but I am working on just compressing everything into a single file that can be minified and served to the browser. Which should work for anything that supports es6. I will most likely have that available tomorrow.

**Comment by ArkinSolomon** [comment]
I've committed a change that will create a script in dist/ that has a minified and non-minified version of everything being compressed into a filed. If you run `npm run build` it should work now I believe?

**Comment by kotx** [comment]
Yup, works very well! Thanks!

**Comment by ArkinSolomon** [comment]
@kotx Do you think you could test it with the 1.2.5 version of the package, by referencing it at `node_modules/discord-emoji-converter/dist/discord-emoji-converter.min.js`

**Comment by kotx** [comment]
It works with `import converter from "discord-emoji-converter/dist/discord-emoji-converter.min.js";` and using it with `converter.getEmoji(...)`, though types are not defined for it.
Also `import { getEmoji } from "discord-emoji-converter/dist/discord-emoji-converter.min.js";` doesn't work.
