### ISSUE TITLE
no such file or directory, open './emojis.json'

### ISSUE THREAD

**Issue by Itz-Hyperz** [ArkinSolomon/discord-emoji-converter#5]
Looking back I see #4 which is concerning to me because this definitely worked before.

I'm on the latest version.

![image](https://cdn.hyperz.net/main/pTKGxu.png)

**Comment by Itz-Hyperz** [comment]
I'm on NodeJS Version 16.13.2

**Comment by Itz-Hyperz** [comment]
did some debugging, changed your index.js file to re-require path and format appropriately.

```js
const path = require('path');

//Load emojis into memory
const emojis = JSON.parse(fs.readFileSync(path.join(__dirname, 'emojis.json'), 'utf8'));
```

**Comment by ArkinSolomon** [comment]
Ok I think I will just re-add path into the package, and anyone who needs to use the compressed version.
